version: "3.3"

services:

  flask:
    build: .
    container_name: flask
    deploy:
      resources:
        reservations:
          memory: 5G
    restart: always
    volumes:
      - ./outputs:/app/outputs
      - ~/.gcp:/app/.gcp/
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.gcp/Audio-Stream-177f9e58ecfc.json
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "5000:80"

